name: UML Designer Documentation
markdown: redcarpet
highlighter: pygments
plugins: [jekyll-paginate, jekyll-gist]
exclude: ['vagrant.sh', 'Vagrantfile', '.vagrant']
paginate: 5
paginate_path: "blog/page:num"
#baseurl: http://uml-designer.github.io/documentation
